export type NOTE_ACTIONS = {
    ADD_NOTE: 'ADD_NOTE',
    EDIT_NOTE: 'EDIT_NOTE',
    DELETE_NOTE: 'DELETE_NOTE',
    DELETE_FROM_TRASH: 'DELETE_FROM_TRASH',
    PIN_NOTE: 'PIN_NOTE',
    ARCHIVE_NOTE: 'ARCHIVE_NOTE',
    SEARCH_NOTE: 'SEARCH_NOTE',
}